import { AVAX, BERA, BNB, CHZ, CORE, ETH, IOTX, POL, SEI, TNT, UOS, XDC, gMELD, xDAI } from "../native-tokens";
import type { SablierChain } from "../types";
import { ChainId } from "./ids";

const mainnets: Record<string, SablierChain> = {
  abstract: {
    explorerURL: "https://abscan.org",
    id: ChainId.ABSTRACT,
    isListedInInterface: true,
    isTestnet: false,
    name: "Abstract",
    nativeToken: ETH,
    rpcURL: "https://api.mainnet.abs.xyz",
  },
  arbitrumOne: {
    explorerURL: "https://arbiscan.io",
    id: ChainId.ARBITRUM_ONE,
    isListedInInterface: true,
    isTestnet: false,
    name: "Arbitrum",
    nativeToken: ETH,
    rpcURL: "https://arbitrum-one-rpc.publicnode.com",
  },
  avalanche: {
    explorerURL: "https://snowtrace.io",
    id: ChainId.AVALANCHE,
    isListedInInterface: true,
    isTestnet: false,
    name: "Avalanche",
    nativeToken: AVAX,
    rpcURL: "https://avalanche-c-chain-rpc.publicnode.com",
  },
  base: {
    explorerURL: "https://basescan.org",
    id: ChainId.BASE,
    isListedInInterface: true,
    isTestnet: false,
    name: "Base",
    nativeToken: ETH,
    rpcURL: "https://base-rpc.publicnode.com",
  },
  berachain: {
    explorerURL: "https://artio.beratrail.io",
    id: ChainId.BERACHAIN,
    isListedInInterface: true,
    isTestnet: false,
    name: "Berachain",
    nativeToken: BERA,
    rpcURL: "https://berachain-rpc.publicnode.com",
  },
  blast: {
    explorerURL: "https://blastscan.io",
    id: ChainId.BLAST,
    isListedInInterface: true,
    isTestnet: false,
    name: "Blast",
    nativeToken: ETH,
    rpcURL: "https://blast-rpc.publicnode.com",
  },
  bsc: {
    explorerURL: "https://bscscan.com",
    id: ChainId.BSC,
    isListedInInterface: true,
    isTestnet: false,
    name: "BNB Smart Chain",
    nativeToken: BNB,
    rpcURL: "https://bsc-rpc.publicnode.com",
  },
  chiliz: {
    explorerURL: "https://scan.chiliz.com",
    id: ChainId.CHILIZ,
    isListedInInterface: true,
    isTestnet: false,
    name: "Chiliz Chain",
    nativeToken: CHZ,
    rpcURL: "https://chiliz.publicnode.com",
  },
  coreDAO: {
    explorerURL: "https://scan.coredao.org",
    id: ChainId.CORE_DAO,
    isListedInInterface: true,
    isTestnet: false,
    name: "Core DAO",
    nativeToken: CORE,
    rpcURL: "https://rpc.coredao.org",
  },
  ethereum: {
    explorerURL: "https://etherscan.io",
    id: ChainId.ETHEREUM,
    isListedInInterface: true,
    isTestnet: false,
    name: "Ethereum",
    nativeToken: ETH,
    rpcURL: "https://ethereum-rpc.publicnode.com",
  },
  form: {
    explorerURL: "https://explorer.form.network",
    id: ChainId.FORM,
    isListedInInterface: true,
    isTestnet: false,
    name: "Form",
    nativeToken: ETH,
    rpcURL: "https://sepolia-rpc.form.network/http",
  },
  gnosis: {
    explorerURL: "https://gnosisscan.io",
    id: ChainId.GNOSIS,
    isListedInInterface: true,
    isTestnet: false,
    name: "Gnosis",
    nativeToken: xDAI,
    rpcURL: "https://gnosis-rpc.publicnode.com",
  },
  iotex: {
    explorerURL: "https://iotexscan.io",
    id: ChainId.IOTEX,
    isListedInInterface: true,
    isTestnet: false,
    name: "IoTeX",
    nativeToken: IOTX,
    rpcURL: "https://babel-api.mainnet.iotex.io",
  },
  lightlink: {
    explorerURL: "https://phoenix.lightlink.io",
    id: ChainId.LIGHTLINK,
    isListedInInterface: true,
    isTestnet: false,
    name: "Lightlink",
    nativeToken: ETH,
    rpcURL: "https://replicator.phoenix.lightlink.io/rpc/v1",
  },
  linea: {
    explorerURL: "https://lineascan.build",
    id: ChainId.LINEA,
    isListedInInterface: true,
    isTestnet: false,
    name: "Linea",
    nativeToken: ETH,
    rpcURL: "https://linea-rpc.publicnode.com",
  },
  meld: {
    explorerURL: "https://meldscan.io",
    id: ChainId.MELD,
    isListedInInterface: false,
    isTestnet: false,
    name: "Meld",
    nativeToken: gMELD,
    rpcURL: "https://rpc-1.meld.com",
  },
  mode: {
    explorerURL: "https://explorer.mode.network",
    id: ChainId.MODE,
    isListedInInterface: true,
    isTestnet: false,
    name: "Mode",
    nativeToken: ETH,
    rpcURL: "https://mainnet.mode.network",
  },
  morph: {
    explorerURL: "https://explorer.morphl2.io",
    id: ChainId.MORPH,
    isListedInInterface: true,
    isTestnet: false,
    name: "Morph",
    nativeToken: ETH,
    rpcURL: "https://rpc.morphl2.io",
  },
  opMainnet: {
    explorerURL: "https://optimistic.etherscan.io",
    id: ChainId.OP_MAINNET,
    isListedInInterface: true,
    isTestnet: false,
    name: "OP Mainnet",
    nativeToken: ETH,
    rpcURL: "https://optimism-rpc.publicnode.com",
  },
  polygon: {
    explorerURL: "https://polygonscan.com",
    id: ChainId.POLYGON,
    isListedInInterface: true,
    isTestnet: false,
    name: "Polygon",
    nativeToken: POL,
    rpcURL: "https://polygon-bor.publicnode.com",
  },
  scroll: {
    explorerURL: "https://scrollscan.com",
    id: ChainId.SCROLL,
    isListedInInterface: true,
    isTestnet: false,
    name: "Scroll",
    nativeToken: ETH,
    rpcURL: "https://scroll-rpc.publicnode.com",
  },
  sei: {
    explorerURL: "https://seitrace.com",
    id: ChainId.SEI,
    isListedInInterface: true,
    isTestnet: false,
    name: "Sei",
    nativeToken: SEI,
    rpcURL: "https://sei-evm-rpc.publicnode.com",
  },
  superseed: {
    explorerURL: "https://seedscan.org",
    id: ChainId.SUPERSEED,
    isListedInInterface: true,
    isTestnet: false,
    name: "Superseed",
    nativeToken: ETH,
    rpcURL: "https://mainnet.superseed.xyz",
  },
  taiko: {
    explorerURL: "https://taikoscan.io",
    id: ChainId.TAIKO,
    isListedInInterface: false,
    isTestnet: false,
    name: "Taiko",
    nativeToken: ETH,
    rpcURL: "https://rpc.mainnet.taiko.xyz",
  },
  tangle: {
    explorerURL: "https://explorer.tangle.tools",
    id: ChainId.TANGLE,
    isListedInInterface: true,
    isTestnet: false,
    name: "Tangle",
    nativeToken: TNT,
    rpcURL: "https://rpc.tangle.tools",
  },
  ultra: {
    explorerURL: "https://evmexplorer.ultra.io",
    id: ChainId.ULTRA,
    isListedInInterface: true,
    isTestnet: false,
    name: "Ultra",
    nativeToken: UOS,
    rpcURL: "https://evm.ultra.eosusa.io",
  },
  unichain: {
    explorerURL: "https://uniscan.xyz",
    id: ChainId.UNICHAIN,
    isListedInInterface: true,
    isTestnet: false,
    name: "Unichain",
    nativeToken: ETH,
    rpcURL: "https://unichain-rpc.publicnode.com",
  },
  xdc: {
    explorerURL: "https://xdcscan.io",
    id: ChainId.XDC,
    isListedInInterface: true,
    isTestnet: false,
    name: "XDC",
    nativeToken: XDC,
    rpcURL: "https://rpc.xdc.org",
  },
  zksyncEra: {
    explorerURL: "https://explorer.zksync.io",
    id: ChainId.ZKSYNC_ERA,
    isListedInInterface: true,
    isTestnet: false,
    name: "zkSync Era",
    nativeToken: ETH,
    rpcURL: "https://mainnet.era.zksync.io",
  },
};

export default mainnets;
