import { ETH, MON } from "../native-tokens";
import type { SablierChain } from "../types";
import { ChainId } from "./ids";

const testnets: Record<string, SablierChain> = {
  arbitrumSepolia: {
    explorerURL: "https://sepolia.arbiscan.io",
    id: ChainId.ARBITRUM_SEPOLIA,
    isListedInInterface: false,
    isTestnet: true,
    name: "Arbitrum Sepolia",
    nativeToken: ETH,
    rpcURL: "https://arbitrum-sepolia-rpc.publicnode.com",
  },
  baseSepolia: {
    explorerURL: "https://sepolia.basescan.org",
    id: ChainId.BASE_SEPOLIA,
    isListedInInterface: true,
    isTestnet: true,
    name: "Base Sepolia",
    nativeToken: ETH,
    rpcURL: "https://base-sepolia-rpc.publicnode.com",
  },
  blastSepolia: {
    explorerURL: "https://sepolia.blastscan.io",
    id: ChainId.BLAST_SEPOLIA,
    isListedInInterface: false,
    isTestnet: true,
    name: "Blast Sepolia",
    nativeToken: ETH,
    rpcURL: "https://sepolia.blast.io",
  },
  ethereumSepolia: {
    explorerURL: "https://sepolia.etherscan.io",
    id: ChainId.ETHEREUM_SEPOLIA,
    isListedInInterface: true,
    isTestnet: true,
    name: "Ethereum Sepolia",
    nativeToken: ETH,
    rpcURL: "https://ethereum-sepolia-rpc.publicnode.com",
  },
  lineaSepolia: {
    explorerURL: "https://sepolia.lineascan.build/",
    id: ChainId.LINEA_SEPOLIA,
    isListedInInterface: false,
    isTestnet: true,
    name: "Linea Sepolia",
    nativeToken: ETH,
    rpcURL: "https://linea-sepolia-rpc.publicnode.com",
  },
  modeTestnet: {
    explorerURL: "https://testnet.modescan.io",
    id: ChainId.MODE_TESTNET,
    name: "Mode Testnet",
    nativeToken: ETH,
    isListedInInterface: false,
    isTestnet: true,
    rpcURL: "https://sepolia.mode.network",
  },
  monadTestnet: {
    id: ChainId.MONAD_TESTNET,
    name: "monad-testnet",
    explorerURL: "https://testnet.monadexplorer.com",
    nativeToken: MON,
    isListedInInterface: false,
    isTestnet: true,
    rpcURL: "https://testnet-rpc.monad.xyz",
  },
  morphHolesky: {
    explorerURL: "https://sepolia.morphscan.io",
    id: ChainId.MORPH_HOLESKY,
    isListedInInterface: false,
    isTestnet: true,
    name: "Morph Holesky",
    nativeToken: ETH,
    rpcURL: "https://rpc-holesky.morphl2.io",
  },
  opSepolia: {
    explorerURL: "https://sepolia-optimism.etherscan.io/",
    id: ChainId.OP_SEPOLIA,
    isListedInInterface: true,
    isTestnet: true,
    name: "OP Sepolia",
    nativeToken: ETH,
    rpcURL: "https://sepolia.optimism.io",
  },
  superseedSepolia: {
    explorerURL: "https://sepolia.seedscan.org",
    id: ChainId.SUPERSEED_SEPOLIA,
    isListedInInterface: false,
    isTestnet: true,
    name: "Superseed Sepolia",
    nativeToken: ETH,
    rpcURL: "https://sepolia.superseed.xyz",
  },
  taikoHekla: {
    explorerURL: "https://hekla.taikoscan.io",
    id: ChainId.TAIKO_HEKLA,
    isListedInInterface: false,
    isTestnet: true,
    name: "Taiko Hekla",
    nativeToken: ETH,
    rpcURL: "https://taiko-hekla-rpc.publicnode.com",
  },
};

export default testnets;
