name: "CI"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v2"

      - name: "Install the Node.js dependencies"
        run: "bun install"

      - name: "Check code with Biome"
        run: "bun run biome ci ."

      - name: "Add summary"
        run: | # shell
          echo "## CI result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
